### ISSUE TITLE
Patternfly templates

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#10069]
Package name TBD but temporarily `patternfly-widgets`.

- [x] #10109
- [x] [Update patternfly-org/react-docs to pull in new package for documentation](https://github.com/patternfly/patternfly-org/issues/3898)
- [x] #10111
- [x] #10112
- [x] #10113
- [x] [Update org to pull in new package](https://github.com/patternfly/patternfly-org/issues/3948)
- [x] #10267
- [ ] Add tests for templates
- [ ] #10339
- [x] #10303

**Comment by thatblindgeye** [comment]
"Template"? E.g. "SelectTemplate", "SelectTypeaheadTemplate", etc.
