### ISSUE TITLE
Updates to update and build latest core

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10314]
We can't build the latest core currently. Steps to get us there:

[details to come]
```[tasklist]
### Tasks
- [x] Remove dropdown styles from menu
- [ ] https://github.com/patternfly/patternfly-react/issues/10316
- [ ] https://github.com/patternfly/patternfly-react/issues/10335
```

**Comment by kmcfaul** [comment]
For tracking, the dropdown styles are removed in my local branch for the TextContent issue that also updates the core version, so I'm marking it as done.

**Comment by kmcfaul** [comment]
Removing the wizard token reference depends on https://github.com/patternfly/patternfly/pull/6447 being done
