### ISSUE TITLE
Update non-deprecated examples to use promoted versions

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#10363]
**Describe the enhancement or change**
Followup to https://github.com/patternfly/patternfly-react/pull/10359 and https://github.com/patternfly/patternfly-react/pull/10358 and similar PRs where components were deprecated, where Next versions were promoted. There are still examples/demos that need to be updated to use the newly promoted implementations:

Any examples/demos in the `deprecated` directory should be fine as-is, but any other instances will need to be updated to use the newly promoted implementations.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/11189
- [ ] https://github.com/patternfly/patternfly-react/issues/11190
- [x] https://github.com/patternfly/patternfly-react/issues/10824
- [ ] https://github.com/patternfly/patternfly-react/issues/11191
- [ ] https://github.com/patternfly/patternfly-react/issues/11192
```

**Comment by thatblindgeye** [comment]
Closing as all subtasks have been completed
