### ISSUE TITLE
PF4: Custom Select Component

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#1206]
This issue will be complete once all the variations of the Custom Select have been implemented. 

- [x] Single Select, issue #1214   
- [x] Checkbox select (multiple items), issue #1217
- [x] Type-ahead select (single item), issue #1215 
- [x] Type-ahead select (multiple items), issue #1216

 Related issue in Core: https://github.com/patternfly/patternfly-next/issues/651  

Info provided on the component: https://docs.google.com/document/d/1rrCdARutABI-Vpa_mdMWGl2xJJTtt2dPQ2bjFx2zwCM/edit?usp=sharing

see: https://pf-next.com/components/Select/examples/

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @srambach (CSS) @mcarrano (interaction design) @christiemolloy (visual design)

**Comment by dgutride** [comment]
Closing via https://github.com/patternfly/patternfly-react/pull/1839
