### ISSUE TITLE
Console errors in test suite

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2847]
Below is a recent list of components that are throwing errors in the jest test suite.

- [ ] VirtualizedTable.test.tsx
- [ ] Alert.test.tsx
- [ ] OptionsMenu.test.tsx
- [ ] SelectToggle.test.tsx
- [ ] DropdownToggle.test.tsx
- [ ] ContextSelectorItem.test.tsx
- [ ] EmptyStateIcon.test.tsx

**Comment by seanforyou23** [comment]
FWIW I see that running the test suite multiple times in a row may generate a slightly different set of results, but the reoccurring theme is that there are several warnings and sometimes errors that could stand to be addressed.

**Comment by seanforyou23** [comment]
I'm able to reproduce the errors consistently now. Updated the description to reflect latest master
