### ISSUE TITLE
Reevaluate DragDrop implementation

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6317]
```[tasklist]
### Tasks
- [ ] Fix animations on examples
- [ ] convert examples to typescript
- [ ] useDroppable to update drop area styles (including when dragging outside droppable area)
- [ ] Make sure you can gracefully cancel a drag
- [x] Build basic example with handle
- [ ] expose props to customize labels for i18n
- [x] https://github.com/patternfly/patternfly-react/issues/6431
- [x] https://github.com/patternfly/patternfly-react/issues/6982
- [x] https://github.com/patternfly/patternfly-react/issues/6723
- [x] https://github.com/patternfly/patternfly-react/issues/7637
```

Follow up issues: 
- [ ] Build basic example with multiple drop zones
- [ ] Build basic draggable table rows example
- [ ] https://github.com/patternfly/patternfly-react/issues/7471

**Comment by redallen** [comment]
This is a little tricky because it also needs to be able to support rows with or without drag handle buttons.

**Comment by nicolethoen** [comment]
https://github.com/patternfly/patternfly-react/pull/6626 is the beginnings of some of the musings... It's not close to working yet.

**Comment by AlexSCorey** [comment]
We brought in the new-ish drag and drop component but ran into some accessibility issues as the user should not drag/drop via keyboard.  If I remove that component in our code ([PR](https://github.com/ansible/awx/pull/11963)) I then begin to get a console warning saying that  onDrag api is deprecated.  I'm in a loop of options that aren't great.  HELP!!
![Screen Shot 2022-03-28 at 11 56 24 AM](https://user-images.githubusercontent.com/39280967/160438594-05dfe56f-edbe-408a-a77b-402394633cef.png)
