### ISSUE TITLE
Dependencies are quite outdated sometimes

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#7287]
Running `yarn outdated` in the root of the project yields quite some outdated dependencies:

<details>
  <summary>yarn outdated</summary>

  ```log
  @babel/core                               7.6.4    7.17.9   7.17.9   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-core                                             
  @babel/plugin-proposal-class-properties   7.5.5    7.16.7   7.16.7   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-plugin-proposal-class-properties                 
  @babel/plugin-proposal-decorators         7.8.3    7.17.9   7.17.9   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-plugin-proposal-decorators                       
  @babel/plugin-proposal-object-rest-spread 7.6.2    7.17.3   7.17.3   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-plugin-proposal-object-rest-spread               
  @babel/plugin-proposal-optional-chaining  7.11.0   7.16.7   7.16.7   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-plugin-proposal-optional-chaining                
  @babel/preset-env                         7.6.3    7.16.11  7.16.11  @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-preset-env                                       
  @babel/preset-react                       7.6.3    7.16.7   7.16.7   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-preset-react                                     
  @babel/preset-typescript                  7.10.4   7.16.7   7.16.7   @patternfly/react-lerna-root             devDependencies https://babel.dev/docs/en/next/babel-preset-typescript                                
  @fortawesome/free-brands-svg-icons        5.14.0   5.15.4   6.1.1    @patternfly/react-icons                  devDependencies https://fontawesome.com                                                               
  @fortawesome/free-regular-svg-icons       5.14.0   5.15.4   6.1.1    @patternfly/react-icons                  devDependencies https://fontawesome.com                                                               
  @fortawesome/free-solid-svg-icons         5.14.0   5.15.4   6.1.1    @patternfly/react-icons                  devDependencies https://fontawesome.com                                                               
  @novnc/novnc                              1.2.0    1.3.0    1.3.0    @patternfly/react-console                dependencies    https://github.com/novnc/noVNC                                                        
  @octokit/rest                             16.43.2  16.43.2  18.12.0  @patternfly/react-lerna-root             devDependencies https://github.com/octokit/rest.js#readme                                             
  @rollup/plugin-commonjs                   21.0.0   21.1.0   21.1.0   @patternfly/react-core                   devDependencies https://github.com/rollup/plugins/tree/master/packages/commonjs/#readme               
  @rollup/plugin-node-resolve               13.0.5   13.2.1   13.2.1   @patternfly/react-core                   devDependencies https://github.com/rollup/plugins/tree/master/packages/node-resolve/#readme           
  @rollup/plugin-replace                    3.0.0    3.1.0    4.0.0    @patternfly/react-core                   devDependencies https://github.com/rollup/plugins/tree/master/packages/replace#readme                 
  @testing-library/jest-dom                 5.16.2   5.16.4   5.16.4   @patternfly/react-lerna-root             devDependencies https://github.com/testing-library/jest-dom#readme                                    
  @testing-library/react                    12.1.2   12.1.5   13.1.1   @patternfly/react-lerna-root             devDependencies https://github.com/testing-library/react-testing-library#readme                       
  @testing-library/user-event               13.5.0   13.5.0   14.1.1   @patternfly/react-lerna-root             devDependencies https://github.com/testing-library/user-event#readme                                  
  @types/d3                                 5.7.2    5.16.4   7.1.0    @patternfly/react-topology               dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3               
  @types/d3-force                           1.2.1    1.2.4    3.0.3    @patternfly/react-topology               dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3-force         
  @types/dagre                              0.7.42   0.7.42   0.7.47   @patternfly/react-topology               dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dagre            
  @types/dom-helpers                        3.4.1    3.4.1    5.0.1    @patternfly/react-virtualized-extension  devDependencies                                                                                       
  @types/file-saver                         2.0.1    2.0.5    2.0.5    @patternfly/react-console                dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/file-saver       
  @types/jest                               27.0.2   27.0.2   27.4.1   @patternfly/react-lerna-root             devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest             
  @types/lodash                             4.14.157 4.14.182 4.14.182 @patternfly/react-charts                 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash           
  @types/react                              17.0.34  17.0.44  18.0.6   @patternfly/react-lerna-root             devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react            
  @types/react                              17.0.34  17.0.44  18.0.6   @patternfly/react-docs                   devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react            
  @types/react                              17.0.34  17.0.44  18.0.6   demo-app-ts                              devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react            
  @types/react-dom                          17.0.11  17.0.15  18.0.2   @patternfly/react-lerna-root             devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom        
  @types/react-dom                          17.0.11  17.0.15  18.0.2   @patternfly/react-docs                   devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom        
  @types/react-dom                          17.0.11  17.0.15  18.0.2   demo-app-ts                              devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom        
  @types/react-measure                      2.0.6    2.0.8    2.0.8    @patternfly/react-topology               dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-measure    
  @types/react-router-dom                   4.3.5    4.3.5    5.3.3    demo-app-ts                              devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router-dom 
  @types/react-virtualized                  9.21.10  9.21.21  9.21.21  @patternfly/react-virtualized-extension  devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-virtualized
  @typescript-eslint/eslint-plugin          4.4.1    4.33.0   5.20.0   @patternfly/react-lerna-root             devDependencies https://github.com/typescript-eslint/typescript-eslint#readme                         
  @typescript-eslint/parser                 4.4.1    4.33.0   5.20.0   @patternfly/react-lerna-root             devDependencies https://github.com/typescript-eslint/typescript-eslint#readme                         
  babel-eslint                              9.0.0    9.0.0    10.1.0   eslint-plugin-patternfly-react           dependencies    https://github.com/babel/babel-eslint                                                 
  babel-jest                                27.2.5   27.5.1   27.5.1   @patternfly/react-lerna-root             devDependencies https://github.com/facebook/jest#readme                                               
  camel-case                                3.0.0    3.0.0    4.1.2    @patternfly/react-styles                 devDependencies https://github.com/blakeembrey/change-case/tree/master/packages/camel-case#readme     
  clean-webpack-plugin                      3.0.0    3.0.0    4.0.0    demo-app-ts                              devDependencies https://github.com/johnagan/clean-webpack-plugin                                      
  concurrently                              5.3.0    5.3.0    7.1.0    @patternfly/react-lerna-root             devDependencies https://github.com/open-cli-tools/concurrently#readme                                 
  concurrently                              5.3.0    5.3.0    7.1.0    @patternfly/react-catalog-view-extension devDependencies https://github.com/open-cli-tools/concurrently#readme                                 
  copy-webpack-plugin                       6.1.0    6.4.1    10.2.4   demo-app-ts                              devDependencies https://github.com/webpack-contrib/copy-webpack-plugin                                
  css                                       2.2.4    2.2.4    3.0.0    @patternfly/react-charts                 devDependencies https://github.com/reworkcss/css#readme                                               
  css                                       2.2.4    2.2.4    3.0.0    @patternfly/react-core                   devDependencies https://github.com/reworkcss/css#readme                                               
  css                                       2.2.4    2.2.4    3.0.0    @patternfly/react-styles                 devDependencies https://github.com/reworkcss/css#readme                                               
  css                                       2.2.4    2.2.4    3.0.0    @patternfly/react-tokens                 devDependencies https://github.com/reworkcss/css#readme                                               
  css-loader                                4.3.0    4.3.0    6.7.1    demo-app-ts                              devDependencies https://github.com/webpack-contrib/css-loader                                         
  cypress                                   8.4.1    8.7.0    9.5.4    @patternfly/react-integration            devDependencies https://github.com/cypress-io/cypress                                                 
  d3                                        5.16.0   5.16.0   7.4.4    @patternfly/react-topology               dependencies    https://d3js.org                                                                      
  dagre                                     0.8.2    0.8.2    0.8.5    @patternfly/react-topology               dependencies    https://github.com/dagrejs/dagre#readme                                               
  eslint                                    7.11.0   7.32.0   8.13.0   @patternfly/react-lerna-root             devDependencies https://eslint.org                                                                    
  eslint-config-airbnb                      16.1.0   16.1.0   19.0.4   eslint-plugin-patternfly-react           dependencies    https://github.com/airbnb/javascript                                                  
  eslint-config-prettier                    2.10.0   2.10.0   8.5.0    eslint-plugin-patternfly-react           dependencies    https://github.com/prettier/eslint-config-prettier#readme                             
  eslint-config-standard                    11.0.0   11.0.0   17.0.0   eslint-plugin-patternfly-react           dependencies    https://github.com/standard/eslint-config-standard                                    
  eslint-config-standard-jsx                5.0.0    5.0.0    11.0.0   eslint-plugin-patternfly-react           dependencies    https://github.com/standard/eslint-config-standard-jsx                                
  eslint-config-standard-react              6.0.0    6.0.0    11.0.1   eslint-plugin-patternfly-react           dependencies    https://github.com/feross/eslint-config-standard-react                                
  eslint-plugin-import                      2.20.2   2.26.0   2.26.0   eslint-plugin-patternfly-react           dependencies    https://github.com/import-js/eslint-plugin-import                                     
  eslint-plugin-jest                        21.27.2  21.27.2  26.1.4   eslint-plugin-patternfly-react           dependencies    https://github.com/jest-community/eslint-plugin-jest#readme                           
  eslint-plugin-jsx-a11y                    6.2.3    6.5.1    6.5.1    eslint-plugin-patternfly-react           dependencies    https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#readme                           
  eslint-plugin-markdown                    1.0.2    1.0.2    2.2.1    @patternfly/react-lerna-root             devDependencies https://github.com/eslint/eslint-plugin-markdown#readme                               
  eslint-plugin-node                        6.0.1    6.0.1    11.1.0   eslint-plugin-patternfly-react           dependencies    https://github.com/mysticatea/eslint-plugin-node#readme                               
  eslint-plugin-prettier                    3.1.4    3.4.1    4.0.0    @patternfly/react-lerna-root             devDependencies https://github.com/prettier/eslint-plugin-prettier#readme                             
  eslint-plugin-prettier                    2.7.0    2.7.0    4.0.0    eslint-plugin-patternfly-react           dependencies    https://github.com/prettier/eslint-plugin-prettier#readme                             
  eslint-plugin-promise                     3.8.0    3.8.0    6.0.0    eslint-plugin-patternfly-react           dependencies    https://github.com/xjamundx/eslint-plugin-promise                                     
  eslint-plugin-react                       7.21.4   7.29.4   7.29.4   @patternfly/react-lerna-root             devDependencies https://github.com/yannickcr/eslint-plugin-react                                      
  eslint-plugin-react                       7.19.0   7.29.4   7.29.4   eslint-plugin-patternfly-react           dependencies    https://github.com/yannickcr/eslint-plugin-react                                      
  eslint-plugin-react-hooks                 4.1.2    4.4.0    4.4.0    eslint-plugin-patternfly-react           dependencies    https://reactjs.org/                                                                  
  eslint-plugin-rulesdir                    0.1.0    0.1.0    0.2.1    eslint-plugin-patternfly-react           dependencies    https://github.com/not-an-aardvark/eslint-plugin-rulesdir#readme                      
  eslint-plugin-standard                    3.1.0    3.1.0    5.0.0    eslint-plugin-patternfly-react           dependencies    https://github.com/standard/eslint-plugin-standard#readme                             
  file-loader                               6.1.0    6.2.0    6.2.0    demo-app-ts                              devDependencies https://github.com/webpack-contrib/file-loader                                        
  file-saver                                1.3.8    1.3.8    2.0.5    @patternfly/react-console                dependencies    https://github.com/eligrey/FileSaver.js#readme                                        
  focus-trap                                6.2.2    6.2.2    6.8.0    @patternfly/react-core                   dependencies    https://github.com/focus-trap/focus-trap#readme                                       
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-lerna-root             devDependencies https://github.com/jprichardson/node-fs-extra                                         
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-charts                 devDependencies https://github.com/jprichardson/node-fs-extra                                         
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-core                   devDependencies https://github.com/jprichardson/node-fs-extra                                         
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-icons                  devDependencies https://github.com/jprichardson/node-fs-extra                                         
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-styles                 devDependencies https://github.com/jprichardson/node-fs-extra                                         
  fs-extra                                  6.0.1    6.0.1    10.1.0   @patternfly/react-tokens                 devDependencies https://github.com/jprichardson/node-fs-extra                                         
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-lerna-root             devDependencies https://github.com/isaacs/node-glob#readme                                            
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-charts                 devDependencies https://github.com/isaacs/node-glob#readme                                            
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-core                   devDependencies https://github.com/isaacs/node-glob#readme                                            
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-icons                  devDependencies https://github.com/isaacs/node-glob#readme                                            
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-styles                 devDependencies https://github.com/isaacs/node-glob#readme                                            
  glob                                      7.1.6    7.2.0    8.0.1    @patternfly/react-tokens                 devDependencies https://github.com/isaacs/node-glob#readme                                            
  html-webpack-plugin                       4.4.1    4.5.2    5.5.0    demo-app-ts                              devDependencies https://github.com/jantimon/html-webpack-plugin                                       
  husky                                     4.3.0    4.3.8    7.0.4    @patternfly/react-lerna-root             devDependencies https://typicode.github.io/husky                                                      
  jest                                      27.2.5   27.2.5   27.5.1   @patternfly/react-lerna-root             devDependencies https://jestjs.io/                                                                    
  jest-cli                                  27.2.5   27.2.5   27.5.1   @patternfly/react-lerna-root             devDependencies https://jestjs.io/                                                                    
  jsdom                                     15.2.1   15.2.1   19.0.0   @patternfly/react-styles                 devDependencies https://github.com/jsdom/jsdom#readme                                                 
  lerna                                     3.22.1   3.22.1   4.0.0    @patternfly/react-lerna-root             devDependencies https://github.com/lerna/lerna#readme                                                 
  lint-staged                               10.4.2   10.5.4   12.4.0   @patternfly/react-lerna-root             devDependencies https://github.com/okonet/lint-staged#readme                                          
  local-web-server                          2.6.1    2.6.1    5.2.0    demo-app-ts                              devDependencies https://github.com/lwsjs/local-web-server#readme                                      
  lodash                                    4.17.20  4.17.21  4.17.21  @patternfly/react-charts                 dependencies    https://lodash.com/                                                                   
  lodash                                    4.17.20  4.17.21  4.17.21  @patternfly/react-table                  dependencies    https://lodash.com/                                                                   
  lodash                                    4.17.20  4.17.21  4.17.21  @patternfly/react-topology               dependencies    https://lodash.com/                                                                   
  memoize-one                               5.2.1    5.2.1    6.0.0    @patternfly/react-log-viewer             dependencies    https://github.com/alexreardon/memoize-one#readme                                     
  mini-css-extract-plugin                   0.11.2   0.11.3   2.6.0    demo-app-ts                              devDependencies https://github.com/webpack-contrib/mini-css-extract-plugin                            
  mobx                                      5.15.6   5.15.7   6.5.0    @patternfly/react-topology               dependencies    https://mobx.js.org/                                                                  
  mobx-react                                6.3.0    6.3.1    7.3.0    @patternfly/react-topology               dependencies    https://mobx.js.org                                                                   
  monaco-editor-webpack-plugin              2.1.0    2.1.0    7.0.1    @patternfly/react-integration            devDependencies https://github.com/microsoft/monaco-editor#readme                                     
  plop                                      2.7.4    2.7.6    3.0.5    @patternfly/react-lerna-root             devDependencies https://plopjs.com                                                                    
  point-in-svg-path                         1.0.1    1.0.2    1.0.2    @patternfly/react-topology               dependencies    https://github.com/maxnachlinger/point-in-svg-path                                    
  prettier                                  1.19.1   1.19.1   2.6.2    @patternfly/react-lerna-root             devDependencies https://prettier.io                                                                   
  react                                     17.0.1   17.0.2   18.0.0   @patternfly/react-lerna-root             devDependencies https://reactjs.org/                                                                  
  react                                     17.0.1   17.0.2   18.0.0   @patternfly/react-docs                   devDependencies https://reactjs.org/                                                                  
  react                                     17.0.1   17.0.2   18.0.0   demo-app-ts                              dependencies    https://reactjs.org/                                                                  
  react-dom                                 17.0.1   17.0.2   18.0.0   @patternfly/react-lerna-root             devDependencies https://reactjs.org/                                                                  
  react-dom                                 17.0.1   17.0.2   18.0.0   @patternfly/react-docs                   devDependencies https://reactjs.org/                                                                  
  react-dom                                 17.0.1   17.0.2   18.0.0   demo-app-ts                              dependencies    https://reactjs.org/                                                                  
  react-dropzone                            9.0.0    9.0.0    12.0.5   @patternfly/react-code-editor            dependencies    https://github.com/react-dropzone/react-dropzone                                      
  react-dropzone                            9.0.0    9.0.0    12.0.5   @patternfly/react-core                   dependencies    https://github.com/react-dropzone/react-dropzone                                      
  react-measure                             2.5.0    2.5.2    2.5.2    @patternfly/react-topology               dependencies    https://github.com/souporserious/react-measure                                        
  react-monaco-editor                       0.41.2   0.41.2   0.47.0   @patternfly/react-integration            devDependencies https://github.com/react-monaco-editor/react-monaco-editor                            
  react-router                              4.3.1    4.3.1    6.3.0    demo-app-ts                              dependencies    https://reactrouter.com/                                                              
  react-router-dom                          4.3.1    4.3.1    6.3.0    demo-app-ts                              dependencies    https://reactrouter.com/                                                              
  react-virtualized                         9.22.2   9.22.3   9.22.3   @patternfly/react-virtualized-extension  dependencies    https://github.com/bvaughn/react-virtualized                                          
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-catalog-view-extension devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-charts                 devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-code-editor            devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-console                devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-core                   devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-docs                   devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-icons                  devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-inline-edit-extension  devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-log-viewer             devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-styles                 devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-table                  devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-tokens                 devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-topology               devDependencies https://github.com/isaacs/rimraf#readme                                               
  rimraf                                    2.7.1    2.7.1    3.0.2    @patternfly/react-virtualized-extension  devDependencies https://github.com/isaacs/rimraf#readme                                               
  rollup                                    2.58.0   2.70.2   2.70.2   @patternfly/react-core                   devDependencies https://rollupjs.org/                                                                 
  sass                                      1.42.1   1.50.1   1.50.1   @patternfly/react-catalog-view-extension devDependencies https://github.com/sass/dart-sass                                                     
  shx                                       0.3.2    0.3.4    0.3.4    @patternfly/react-catalog-view-extension devDependencies https://github.com/shelljs/shx#readme                                                 
  shx                                       0.3.2    0.3.4    0.3.4    @patternfly/react-docs                   devDependencies https://github.com/shelljs/shx#readme                                                 
  surge                                     0.21.6   0.21.7   0.23.1   @patternfly/react-lerna-root             devDependencies https://github.com/sintaxi/surge#readme                                               
  theme-patternfly-org                      0.11.22  0.11.22  0.11.28  @patternfly/react-docs                   devDependencies                                                                                       
  tippy.js                                  5.1.2    5.1.2    6.3.7    @patternfly/react-core                   dependencies    https://atomiks.github.io/tippyjs/                                                    
  ts-loader                                 8.0.4    8.3.0    9.2.8    demo-app-ts                              devDependencies https://github.com/TypeStrong/ts-loader                                               
  ts-loader                                 8.0.17   8.3.0    9.2.8    @patternfly/react-integration            devDependencies https://github.com/TypeStrong/ts-loader                                               
  ts-patch                                  1.4.2    1.4.5    2.0.1    @patternfly/react-lerna-root             devDependencies https://github.com/nonara/ts-patch#readme                                             
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-lerna-root             devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-catalog-view-extension devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-charts                 devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-code-editor            devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-console                devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-core                   devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-icons                  devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-inline-edit-extension  devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    demo-app-ts                              devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-integration            devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-log-viewer             devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-styles                 devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-table                  devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-topology               devDependencies https://www.typescriptlang.org/                                                       
  typescript                                4.3.5    4.6.3    4.6.3    @patternfly/react-virtualized-extension  devDependencies https://www.typescriptlang.org/                                                       
  url-loader                                4.1.0    4.1.1    4.1.1    demo-app-ts                              devDependencies https://github.com/webpack-contrib/url-loader                                         
  victory-area                              36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-axis                              36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-bar                               36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-chart                             36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-core                              36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-create-container                  36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-group                             36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-legend                            36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-line                              36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-pie                               36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-scatter                           36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-stack                             36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-tooltip                           36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-voronoi-container                 36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  victory-zoom-container                    36.2.1   36.3.2   36.3.2   @patternfly/react-charts                 dependencies    https://formidable.com/open-source/victory                                            
  webpack                                   4.44.1   4.46.0   5.72.0   demo-app-ts                              devDependencies https://github.com/webpack/webpack                                                    
  webpack                                   4.44.1   4.46.0   5.72.0   @patternfly/react-integration            devDependencies https://github.com/webpack/webpack                                                    
  webpack-cli                               3.3.12   3.3.12   4.9.2    demo-app-ts                              devDependencies https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli               
  xterm                                     4.9.0    4.18.0   4.18.0   @patternfly/react-console                dependencies    https://github.com/xtermjs/xterm.js#readme                                            
  xterm-addon-fit                           0.2.1    0.2.1    0.5.0    @patternfly/react-console                dependencies    https://github.com/xtermjs/xterm.js#readme         
  ```

</details>

Perhaps it's a good idea to set up [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) or expand [Renovate](https://docs.renovatebot.com/) to also upgrade other dependencies?

- [x] patternfly/patternfly-react#7314
- [x] patternfly/patternfly-react#7315
- [x] patternfly/patternfly#4816
- [x] patternfly/patternfly#4817
- [x] patternfly/patternfly-react#7320

**Comment by thatblindgeye** [comment]
Since the tasks are completed in this issue, and we have https://github.com/patternfly/patternfly-react/issues/11491 tracking a latest list of dep bumps necessary, will be closing this one out
