### ISSUE TITLE
Dual list selector - create dual list selector next

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#8700]
Rather than simultaneously maintain four implementations of the dual list selector:
1. dynamic list style dual list selector
2. dynamic tree style dual list selector
3. composable list style dual list selector
4. composable tree style dual list selector
We should instead only be maintaining one. All four types of the dual list selector should be able to be implemented using the composable tree building blocks.

We could still also export an additional implementation, which will compose the most basic list and tree styles automatically. Almost like exportable demos.

- [ ] remake all existing examples using tree style dual list selector
- [ ] remove the wiring for the dynamic list and tree configurations
- [ ] wrap and make export-able the basic tree and list examples 

Be sure the next implementation addresses the following issues:
- [ ] https://github.com/patternfly/patternfly-react/issues/7548
- [ ] https://github.com/patternfly/patternfly-react/issues/6213
- [ ] https://github.com/patternfly/patternfly-react/issues/7538
- [ ] https://github.com/patternfly/patternfly-react/issues/7021
