### ISSUE TITLE
RTL - Core followup for RTL changes

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#9521]
**Goal**
The core team is implementing RTL support and some components may require react followup. 

This is a placeholder issue until testing is complete.

Check components:

- [x] patternfly/patternfly-react#9585
- [x] Accordion
- [x] Action list
- [x] Alert
- [x] Avatar
- [x] Back to top
- [x] Background image
- [x] Badge
- [x] Banner
- [x] Brand
- [x] patternfly/patternfly-react#9587
- [x] patternfly/patternfly-react#9589
- [x] Calendar month
- [x] Card
- [x] patternfly/patternfly-react#9590
- [x] Chip
- [x] patternfly/patternfly#5926
- [x] Code block
- [x] Code editor
- [x] patternfly/patternfly-react#9591
- [x] Date picker
- [x] Date and time picker
- [x] Description list
- [x] Divider
- [x] Drag and drop
- [x] patternfly/patternfly-react#9596
- [x] patternfly/patternfly-react#9594
- [x] Dual list selector
- [x] Empty state
- [x] Expandable section
- [x] File upload
- [x] File upload - multiple
- [x] Form
- [x] Form control
- [x] Form select
- [x] Helper text
- [x] Hint
- [x] patternfly/patternfly-react#9595
- [x] Input group
- [x] Jump links
- [x] Label
- [x] List
- [x] Login page
- [x] Masthead
- [x] Menu - breadcrumb drilldown arrow PR https://github.com/patternfly/patternfly-react/pull/9603
- [x] Menu toggle
- [x] Modal
- [x] patternfly/patternfly-react#9607
- [x] Notification badge
- [x] Notification drawer
- [x] Number input
- [x] Overflow menu
- [x] Page
- [x] patternfly/patternfly-react#9599
- [x] Panel
- [x] patternfly/patternfly-react#9608
- [x] Progress
- [x] Progress stepper
- [x] Radio
- [x] Search input
- [x] Select
- [x] Sidebar
- [x] Simple list
- [x] Skeleton
- [x] Skip to content
- [x] patternfly/patternfly-react#9593
- [x] Spinner
- [x] Switch
- [x] patternfly/patternfly-react#9597
- [x] Text
- [x] Text area
- [x] Text input
- [x] Text input group
- [x] Tile
- [x] Time picker
- [x] Timestamp
- [x] Title
- [x] Toggle group
- [x] Toolbar
- [x] Tooltip
- [x] Tree view
- [x] Truncate
- [x] patternfly/patternfly-react#9586

**Comment by wise-king-sullyman** [comment]
One item that will be needed as part of this: reviewing the components in React and identifying any issues with the final React implementation after pulling in the updated styles from core.

**Comment by thatblindgeye** [comment]
Just jotting down to keep in mind: DataList and Date Picker examples will have to be checked once/if any update to Popper is implemented to support RTL. DataList has some kebab dropdowns that end up being aligned incorrectly in RTL, DatePicker uses Popover internally which ends up having the arrow positioned incorrectly in RTL.

DataList example with a dropdown menu in RTL:

![image](https://github.com/patternfly/patternfly-react/assets/70952936/f9189927-0831-485a-8a1d-e03df82d2a04)

DatePicker in RTL:

![image](https://github.com/patternfly/patternfly-react/assets/70952936/f47437de-df49-41f5-9adb-d86bd3a85a93)

**Comment by mcoker** [comment]
@kmcfaul currently, there is a CSS var `--pf-v5--inverse--multiplier` with a value set to 1 or -1 depending on whether you're in an LTR or RTL block via the `dir` attribute value or using `.pf-v5-m-dir-[ltr/rtl]`. You can get the val using this technique https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#values_in_javascript

```
getComputedStyle(element).getPropertyValue("--pf-v5--inverse--multiplier")

// value is 1 if the element tested or an ancestor of the tested element has 1) no 'dir' is set, 2) has 'dir="ltr"', or 3) has 'class="pf-v5-m-dir-ltr'
// value is -1 if (same as above) but 1) 'dir="rtl"' or 2) 'class="pf-v5-m-dir-rtl"'
```

**Comment by srambach** [comment]
The dropdowns in the toolbar demo need to be checked once the dropdown menu is fixed up to switch l/r when there isn't room. https://react-staging.patternfly.org/components/toolbar/react-demos/console-log-viewer-toolbar-demo/

**Comment by wise-king-sullyman** [comment]
All items in this epic have been completed 🎉
