### ISSUE TITLE
Consume core updates: Button, Toggle Group, Notification Badge

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#9675]
Follow up to core issue for [Buttons...](https://github.com/patternfly/patternfly/issues/5717)
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/9907
- [ ] https://github.com/patternfly/patternfly-react/issues/9982
- [ ] https://github.com/patternfly/patternfly-react/issues/9811
```
