### ISSUE TITLE
Migration guides for deprecated components

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#9820]
A skeleton of the guides we want to write has been created in [this doc](https://docs.google.com/document/d/11_6Xe-E1HbGYCoOK0clq-dEN-hujPUtD-EF6vH4-c80/edit#heading=h.ii0as9329z73).

```[tasklist]
### Tasks
- [x] Table - sortable
- [x] Table - selectable
- [x] Table - expandable
- [x] Table - compound expandable
- [x] Table - with actions
- [x] Table - empty state
- [x] Table - favoriable
- [x] Table - tree
- [ ] Table modifiers
- [x] Select - single
- [x] Select - checkbox
- [x] Select - typeahead
- [ ] Select - with inline filtering
- [ ] Select - modifiers
- [ ] Select - composable favorites
- [ ] Select - composable custom panel
- [ ] Dropdown - basic
- [ ] Dropdown - tooltips on disabled items
- [ ] Dropdown - with autofocus
- [ ] Dropdown - toggle styles
- [ ] Dropdown - menu behaviors
- [ ] Dropdown modifiers
- [ ] Wizard (guides TBD)
- [ ] Application launcher (guides TBD)
- [ ] Context selector (guides TBD)
- [ ] Options menu (guides TBD)
- [ ] Page header (guides TBD)
```

We will also want to incorporate any information from @mturley's table batteries effort
