### ISSUE TITLE
Consume core updates:  Avatar, Brand, Background image, Backdrop, Divider, Truncate, Icon ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9879]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/9880
- [ ] https://github.com/patternfly/patternfly-react/issues/9921
- [ ] https://github.com/patternfly/patternfly-react/issues/9914
- [ ] https://github.com/patternfly/patternfly-react/issues/9920
- [ ] https://github.com/patternfly/patternfly-react/issues/9919
- [ ] https://github.com/patternfly/patternfly-react/issues/9918
- [ ] https://github.com/patternfly/patternfly-react/issues/9988
```

**Comment by tlabaj** [comment]
all tasks closed
