### ISSUE TITLE
Consume core updates: Simple list, Data list and Description list ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9924]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/9926
- [ ] https://github.com/patternfly/patternfly-react/issues/9925
- [ ] https://github.com/patternfly/patternfly-react/issues/9987
```
