### ISSUE TITLE
Consume core updates: Code block, Code editor and Clipboard copy ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9999]
Follow up to core issue https://github.com/patternfly/patternfly/issues/5735

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/10000
- [ ] https://github.com/patternfly/patternfly-react/issues/10001
- [ ] https://github.com/patternfly/patternfly-react/issues/10002
```

**Comment by tlabaj** [comment]
All tasks closed
